version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: everdrive-nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
        #- /home/ubuntu/ssl:/ssl/
  php:
    image: php:8.0-fpm-alpine
    container_name: everdrive-php
    expose:
      - 9000:9000
    volumes:
      - ./src:/var/www/html

