version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: everdrive-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      #- ./config/nginx_ssl.conf:/etc/nginx/conf.d/default.conf # ENABLE SSL
      - ./config/certs:/etc/certs/
      - ./public:/var/www/html
        #- /home/ubuntu/ssl:/ssl/
  php:
    image: php:8.0-fpm-alpine
    container_name: everdrive-php
    volumes:
      - ./src:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
